INSERT INTO regiones (id, name) VALUES (1,'Sudamérica');
INSERT INTO regiones (id, name) VALUES (2,'Centroamérica');
INSERT INTO regiones (id, name) VALUES (3,'Norteamérica');
INSERT INTO regiones (id, name) VALUES (4,'Europa');
INSERT INTO regiones (id, name) VALUES (5,'Asia');
INSERT INTO regiones (id, name) VALUES (6,'Africa');
INSERT INTO regiones (id, name) VALUES (7,'Oceanía');
INSERT INTO regiones (id, name) VALUES (8,'Antártida');

INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(1, 'Roger', 'Pomacarhua', 'roger@gmail.com', '2018-01-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(2, 'Juan', 'Marquina', 'juan@gmail.com', '2018-02-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(2, 'Pablo', 'Escobar', 'pablo@gmail.com', '2019-03-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(1, 'Roger', 'Pomacarhua', 'roger1@gmail.com', '2018-01-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(3, 'Juan', 'Marquina', 'juan1@gmail.com', '2018-02-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(4, 'Pablo', 'Escobar', 'pablo1@gmail.com', '2019-03-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(5, 'Roger', 'Pomacarhua', 'roge2r@gmail.com', '2018-01-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(5, 'Juan', 'Marquina', 'juan2@gmail.com', '2018-02-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(5, 'Pablo', 'Escobar', 'pablo2@gmail.com', '2019-03-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(6, 'Roger', 'Pomacarhua', 'roger3@gmail.com', '2018-01-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(6, 'Juan', 'Marquina', 'juan3@gmail.com', '2018-02-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(2, 'Pablo', 'Escobar', 'pablo3@gmail.com', '2019-03-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(3, 'Roger', 'Pomacarhua', 'roger4@gmail.com', '2018-01-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(2, 'Juan', 'Marquina', 'juan4@gmail.com', '2018-02-01');
INSERT INTO clients (region_id, name, lastname, email, created_at) VALUES(8, 'Pablo', 'Escobar', 'pablo4@gmail.com', '2019-03-01');